# Generated by Django 2.2.2 on 2019-06-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Contatos',
        ),
    ]
